# Paths configuration
paths:
  output_path: './output' # Directory where generated files are saved

keys:
  openai-key: OPENAI_KEY

# ChatGPT settings
chat_gpt:
  model: 'gpt-4o' # ChatGPT model to use
  max_tokens: 16000 # Token limit for each generated file
  temperature: 0.6 # Control creativity of responses
