# default settings for all prompts
defaults:
  settings:
    role: |
      You are a senior software developer proficient in multiple programming languages.
    code_style: |
      clean code

prompts:
  # Generating idea for a future application
  idea:
    prompt: |
      Provide an idea for a web application on python. Name must be a snake_case, description up to 20 words
    description: 'Suggests ideas for new applications.'

  # Make structure for code
  structure:
    prompt: |
      Give me a list of 20-25 files for app we discussed before. Print a path without '/' on the start and with '/' in the end and file name without any '/'. Do also main file. 
      Make all paths from main file path of project, don't use application name. Do not use images, html files etc. Only Python files.
      But don't forget about 'Makefile', 'Dockerfile', 'docker-compose', 'package.json', '.gitignore', 'README.md', '.env.example' files in the root of the project.
      Use clean architecture for flask web app.
    description: 'Creates the initial structure for an application.'

  # Request code for a specific file
  code:
    prompt: |
      Write the full code for {file_path}. Ensure all files interact properly. 
      Do not use an examples in the code, just clean code, as a real project.
      If it is Readme.file, mention in code, that project created by Openai API.
      Limit the code from 50 to 100 lines. Provide only the code, without markdown. Use few comments in English only.
    description: 'Generates code for specific modules based on requirements.'

  # Generate a commit message
  commit:
    prompt: |
      Create a concise commit message for adding {file_path}. Make a short but clear comment. 
      Use creative commit messages. Don't repeat yourself.
      Do not use quotes. Make a short commit message, up to 7 words.
    description: 'Provides clear and concise commit messages.'
