# default settings for all prompts
defaults:
  settings:
    role: |
      You are a senior software developer proficient in multiple programming languages.
    code_style: |
      clean code

prompts:
  # Generating idea for a future application
  idea:
    prompt: |
      Provide an idea for a web application on python consisting of 10-20 files. Name must be a snake_case, description up to 20 words
    description: 'Suggests ideas for new applications.'

  # Make structure for code
  structure:
    prompt: |
      List of file names for app we discussed before. Print a file with location (app/main.py, etc...). Use clean architecture for flask web app.
    description: 'Creates the initial structure for an application.'

  # Request code for a specific file
  code:
    prompt: |
      Write the code for {file_path}. Ensure all files interact properly. 
      Limit the code from 50 to 100 lines. Provide only the code, without markdown. Use few comments, in English only.
    description: 'Generates code for specific modules based on requirements.'

  # Generate a commit message
  commit:
    prompt: |
      Create a concise commit message for adding {file_path}. Make a short but clear comment.
    description: 'Provides clear and concise commit messages.'
